# Site settings
title: Brom [ ] Diki Andriansyah A P
email: diki1aap@gmail.com
description: Brom [ ] Diki Andriansyah A P sebuah blog room yang saya kelola untuk membagikan tulisan dan aktivitas saya, seperti pengetahuan, pengamatan dan informasi di penulisan kode.
baseurl: ""
url: "https://dikiaap.github.io"
subtitle: Brom brom code brom !!
keywords: "Diki Andriansyah A P, Brom [ ] Diki Andriansyah A P, Brom Diki Andriansyah A P, Brom Diki Andriansyah, dikiaap, Diki Andriansyah Ananta Putra, Diki Andriansyah, dikiaap.github.io"
sosial_username: dikiaap
simple_search: http://google.com/search
# Build settings
markdown: kramdown
author: dikiaap
permalink: ":year/:month/:day/:title/"
paginate: 7
paginate_path: "/page/:num/"
gems:
  - jekyll-sitemap