# Site settings ...
uri: mangan.dikiaap.id
url: https://mangan.dikiaap.id
name: Your name
title: Mangan Jekyll Theme
email: example@domain.com
author: username
baseurl: ""
keywords: "Mangan, Jekyll, Theme"
description: "Geek theme for Jekyll."
social_username: username

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
